# Generated by Django 3.0.5 on 2020-07-10 16:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(default='India', max_length=2)),
                ('desc', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Art_Name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=150)),
                ('Image', models.ImageField(default='', upload_to='images/')),
                ('price', models.FloatField(default=0)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Art_app.Artist')),
            ],
        ),
    ]
