# Generated by Django 3.0.5 on 2020-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_app', '0003_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
